#!/usr/bin/env bash
set -euf -o pipefail

# INSTALL DOCKER
sudo apt-get update
sudo apt-get install -y ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# END DOCKER

DIR="$(dirname "$(realpath "$0")")"
PREFIX='/opt/posthog'

mkdir -p "$PREFIX"
cd "$PREFIX"
$DIR/deploy-hobby 'latest' "$(ec2-metadata -p | cut -d' ' -f2)"

